### ISSUE TITLE
use a Boolean class

### ISSUE THREAD

**Issue by jwaldmann** [adamwalker/haskell_cudd#10]
Can we make `DDNode` an instance of (a class like) https://hackage.haskell.org/package/ersatz-0.3.1/docs/Ersatz-Bit.html#t:Boolean ? 

If yes, then we could write  polymorphic formulas: *one* piece of code that produces a formulat that I can
* evaluate, given an assignment
* ask a SAT solver for a model
* ask a BDD implementation for number of models, etc.

But no, we cannot, since we need the DDmanager. Or - we can do as `ersatz` does, and just construct an AST, which will be sent to a back-end only later. This needs observable sharing (in ersatz: to detect whether we already Tseitin-transformed an expression to a literal, in cudd: whether we already have the DDnode for the expression). Looks like another optional layer for the Cudd API.

**Comment by adamwalker** [comment]
Sounds like another good interface. However, I think it would be best to keep this library as a relatively low level wrapper around CUDD that more advanced interfaces like the one you're proposing can be built on top of. 

I can point to this separate package from my readme for people who are looking for a nicer high level interface.

**Comment by jwaldmann** [comment]
I made this: https://github.com/jwaldmann/cudd-ersatz

**Comment by adamwalker** [comment]
Looks nice! Would you like me to link to it from readme in my CUDD bindings? Is it mature enough yet?

**Comment by jwaldmann** [comment]
I'd appreciate if you reference cudd-ersatz. Mature? Well, I have a few tests that show that it works, but I'm quite sure I need to add more stuff to the API for convenience. E.g., for getting (some, all) models, I should like to have something like https://hackage.haskell.org/package/ersatz-0.3.1/docs/Ersatz-Codec.html#t:Codec .

**Comment by adamwalker** [comment]
I have referenced it in the markdown readme as well as the cabal file.
