### ISSUE TITLE
lazily calculate allSat

### ISSUE THREAD

**Issue by maweki** [adamwalker/haskell_cudd#5]
I am working on bdds with many solutions and the functional interface is very nice to handle.

Now I need to generate all solutions but the solutions take an extreme amount of memory and I would like to lazily generate them (so not using allSat, which allocates all the needed memory). It there a way to use a functionally created manager/bdd within the ST-monad and use firstCube and nextCube to then lazily filter over the solutions?

**Comment by maweki** [comment]
Sorry, found it in convert

**Comment by adamwalker** [comment]
Yeah, I probably need to improve the documentation a bit.
