### ISSUE TITLE
how to install on Fedora (using their cudd package)

### ISSUE THREAD

**Issue by jwaldmann** [adamwalker/haskell_cudd#6]
This works, we just need:

```
    extra-libraries:     cudd, mtr, cuddst, cuddutil, epd, dddmp, m
    extra-include-dirs: /usr/include/cudd
```

see https://github.com/adamwalker/cudd/issues/1

**Comment by jwaldmann** [comment]
Fedora 24 has packaged cudd-3.0.0, file layout (ignoring documentation) is:

```
$ repoquery -lq --installed cudd

/usr/lib64/libcudd-3.0.0.so.0
/usr/lib64/libcudd-3.0.0.so.0.0.0

$ repoquery -lq --installed cudd-devel

/usr/include/cudd
/usr/include/cudd/config.h
/usr/include/cudd/cudd.h
/usr/include/cudd/cuddInt.h
/usr/include/cudd/cuddObj.hh
/usr/include/cudd/dddmp.h
/usr/include/cudd/epd.h
/usr/include/cudd/mtr.h
/usr/include/cudd/st.h
/usr/include/cudd/util.h
/usr/lib64/libcudd.so
```

so I think this only needs

```
    extra-libraries:     cudd
    extra-include-dirs: /usr/include/cudd
```

It compiles fine, I am currently testing larger examples. (The risk is of course that your `c_sources/*.c` would not match what's in the new version.)

**Comment by adamwalker** [comment]
Sorry for the slow reponse. I remember reading this bug report and then for some reason I completely forgot about it.
This is fixed, basically as you describe, in the cudd-3.0.0 branch. I will merge that to master and update Hackage.

**Comment by adamwalker** [comment]
I have updated the version on Hackage and the instructions for cudd 3.0.0. Does it work for you?

**Comment by jwaldmann** [comment]
With Fedora's `cudd-devel` package installed, I can compile `haskell_cudd` with
```
cabal install --extra-include-dirs=/usr/include/cudd
```
and `extra-lib-dirs` is not needed.

I suggest
* mention this in the README
* drop `extra-lib-dirs` from the cabal file (you can never know where the user puts his libraries)

**Comment by adamwalker** [comment]
Interestingly, I only needed --extra-lib-dirs=/usr/local/lib and not --extra-include-dirs.

I dropped the extra dirs from the readme and added a note to the cabal file and readme as suggested.

**Comment by jwaldmann** [comment]
> ... no extra-include-dirs

There is `#include "cudd.h"` in `c_sources/stubs.c`. From where does the (C) compiler know that this file is in `/usr/include/cudd/cudd.h`?

**Comment by adamwalker** [comment]
The include files are in /usr/local/include on my mahcine. I'm not sure if thats because the autotools build system of Cudd 3.0 put them there or because I did manually. /usr/local/include is in my library search path, which is how it finds them.

**Comment by jwaldmann** [comment]
I see. I was talking not about "installing cudd from source on fedora" but "installing the fedora cudd-devel package", see second message in this thread.
