### ISSUE TITLE
exact model count (provide binding for Cudd_ApaCountMinterm)

### ISSUE THREAD

**Issue by jwaldmann** [adamwalker/haskell_cudd#8]
The number of models of a BDD (the number of "minterms") is returned by `countMinterm` as a Double.
(It cannot be an `int`, because that would overflow too easily. But the Double has rounding issues,
and it still can overflow.)

CUDD actually provides an exact model count:  Cudd_ApaCountMinterm ( http://vlsi.colorado.edu/~fabio/CUDD/html/cudd_8h.html#a86d07f6e04e77467e44c0d209c3b450d ) . This returns an APA - in Haskell, that would just be `Integer`, but we need some marshalling here.

**Comment by adamwalker** [comment]
Sounds like a good idea. I'm happy to take pull requests :)

**Comment by jwaldmann** [comment]
I'll look into it.  We can read the DdApaNumber returned from  Cudd_ApaCountMinterm with http://hackage.haskell.org/package/base-4.9.0.0/docs/Foreign-Marshal-Array.html#v:peekArray
I'm not sure how CUDD's memory manager handles the APA space afterwards.

**Comment by adamwalker** [comment]
Neither am I, but it might be necessary to free it with Cudd_FreeApaNumber here: http://vlsi.colorado.edu/~fabio/CUDD/html/cuddApa_8c.html.
